Repository QuantEcon/lecture-python, pull requests merged in 2020-04, with the labels that each got.

#77 cake_eating_problem_typo
  source/rst/cake_eating_problem.rst
Labels: ready

#96 cake_eating_numerical_issue2
  source/rst/cake_eating_numerical.rst
Labels: in-work

#95 cake_eating_numerical_issue1
  source/rst/cake_eating_numerical.rst
Labels: in-work

#97 cake_eating_numerical_issue3
  source/rst/cake_eating_numerical.rst
Labels: in-work

#98 cake_eating_numerical_issue4
  source/rst/cake_eating_numerical.rst
Labels: in-work

#106 remove_author
  source/_static/lecture_specific/markov_perf/duopoly_mpe.py
Labels: ready

#107 optgrowth1_typos
  source/rst/optgrowth.rst
Labels: ready

#111 optgrowth1_clarifyshock
  source/rst/optgrowth.rst
Labels: in-work

#110 optgrowth1_attachlinks
  source/rst/optgrowth.rst
Labels: in-work

#108 optgrowth1_punctuation
  source/rst/optgrowth.rst
Labels: ready

#123 minor fix in coleman
  source/rst/coleman_policy_iter.rst
Labels: in-work

#125 complex numbers issue
  source/rst/complex_and_trig.rst
Labels: ready

#152 minor typo
  source/rst/cass_koopmans_1.rst
Labels: bug
